# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appmanual.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import ipaddress
import math
import logo

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(636, 871)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 90, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 210, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 270, 121, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(30, 110, 201, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 230, 201, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 290, 201, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 330, 91, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 350, 201, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 390, 91, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 410, 201, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 450, 91, 16))
        self.label_6.setObjectName("label_6")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(30, 470, 551, 381))
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(490, 110, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.subnet)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 150, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.delete)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(160, 20, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(30, 170, 201, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 150, 91, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(390, 290, 191, 171))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "IP ADDRESS"))
        self.label_2.setText(_translate("Form", "No. of borrow bits"))
        self.label_3.setText(_translate("Form", "SUBNET MASK"))
        self.label_4.setText(_translate("Form", "CLASS"))
        self.label_5.setText(_translate("Form", "HOST/SUBNET"))
        self.label_6.setText(_translate("Form", "HOST ADDRESS"))
        self.pushButton.setText(_translate("Form", "OK"))
        self.pushButton_2.setText(_translate("Form", "CLEAR"))
        self.label_7.setText(_translate("Form", "SUBNET CALCULATOR"))
        self.label_8.setText(_translate("Form", "No. of SUBNET"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/Screenshot 2022-04-18 071539.jpg\"/></p></body></html>"))


    #main program:
    def subnet(self):
        a = self.lineEdit.text()
        k = self.lineEdit_6.text()
        n = math.ceil(math.log(int(k),2))
        self.lineEdit_2.setText(str(n))
        b = ipaddress.IPv4Network(a)
        c = list(b.subnets(prefixlen_diff=int(n)))
        d = c[0].netmask
        m = []
        for i in c[0].hosts():
            m.append(i)
        self.lineEdit_3.setText(str(d))
        self.lineEdit_5.setText(str(len(m)))
        l = a.split('/')
        k = l[0].split('.')
        if int(k[0]) >= 0 and int(k[0]) <= 127:
            self.lineEdit_4.setText('Class A')
        elif int(k[0]) >= 128 and int(k[0]) <= 191:
            self.lineEdit_4.setText('Class B')
        elif int(k[0]) >= 192 and int(k[0]) <= 223:
            self.lineEdit_4.setText('Class C')

        for j in range(len(c)):
            self.listWidget.addItem(str('Subnet {}:'.format(str(j+1))))
            t = []
            for i in c[j].hosts():
                t.append(i)
            self.listWidget.addItem(str('Network ID: {}'.format(str(c[j].network_address))))
            self.listWidget.addItem(str('Broadcast ID: {}'.format(str(c[j].broadcast_address))))
            self.listWidget.addItem(str('Host range: {} --> {}'.format(str(t[0]),str(t[-1]))))
            self.listWidget.addItem(str('------------------------------------------'))

    def delete(self):
        self.lineEdit.setText('')
        self.lineEdit_2.setText('')
        self.lineEdit_3.setText('')
        self.lineEdit_4.setText('')
        self.lineEdit_5.setText('')
        self.lineEdit_6.setText('')
        self.listWidget.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
